TARGET := dhrystone

C_SRCS := dhry_stubs.c dhry_1.c dhry_2.c 
HEADERS := dhry.h

CFLAGS := -O2  -fno-inline -fno-common -falign-labels=4  -falign-functions=4 -falign-jumps=4 -falign-loops=4


BSP_BASE = ../../hbird_e203_bsp
include $(BSP_BASE)/env/common.mk

